basys:
  controlcomponent:
    id: drone_1
    name: Drone-1
    operationModeJavaPackage: de.dfki.cos.basys.controlcomponent.example.calc.opmodes
    initialExecutionMode: SIMULATE
    executionModes:
      simulate:
        executionModeChangeDisabled: true
        occupationCheckDisabled: true
#        service:
#          implementationJavaClass: de.dfki.cos.basys.controlcomponent.example.math.service.CalculationServiceImpl
#          connectionString: simulateConnectionString
#          properties:
#            prop2: value2
      auto:
        executionModeChangeDisabled: true
        occupationCheckDisabled: true
        service:
          implementationJavaClass: de.dfki.cos.basys.controlcomponent.example.calc.CalculationServiceImpl
          connectionString: autoConnectionString
          properties:
            prop1: value1